### ISSUE TITLE
How does the ratio plot deal with N's corresponding to proportions

### ISSUE THREAD

**Issue by Al-Murphy** [emiliecottard/Shiny_App#3]
Like to know your thoughts, I feel like they may need to be excluded from the plot as I don't see how you could accurately calculate them

**Comment by emiliecottard** [comment]
I am not sure I get what you mean. Do you mean N for publications where values are already a percent of control in the raw dataset ?

**Comment by Al-Murphy** [comment]
Discussed in chat, happy it's dealt with accordingly
